### ISSUE TITLE
Issues making a docker-compose

### ISSUE THREAD

**Issue by JoshuaRL** [kokofixcomputers/1min-relay#23]
Hello, I'm trying to take your docker run directions and turn them into a workable docker-compose. I've gotten this far but it's failing at memcached. Any suggestions?

```
version: '3.9'
services:
     memcached:
        build: https://github.com/kokofixcomputers/1min-relay.git
        command: pull memcached:latest
        networks:
            1min-relay-network: {}
        container_name: memcached
     1min-relay:
        build: https://github.com/kokofixcomputers/1min-relay.git
        command: pull kokofixcomputers/1min-relay:latest
        environment:
            - SUBSET_OF_ONE_MIN_PERMITTED_MODELS="mistral-nemo,gpt-4o-mini,deepseek-chat"
            - PERMIT_MODELS_FROM_SUBSET_ONLY=True
        ports:
            - '5001:5001'
        networks:
            1min-relay-network: {}
        container_name: 1min-relay-container
1min-relay-network: {}

```

**Comment by kokofixcomputers** [comment]
> Hello, I'm trying to take your docker run directions and turn them into a workable docker-compose. I've gotten this far but it's failing at memcached. Any suggestions?
> 
> ```
> version: '3.9'
> services:
>      memcached:
>         build: https://github.com/kokofixcomputers/1min-relay.git
>         command: pull memcached:latest
>         networks:
>             1min-relay-network: {}
>         container_name: memcached
>      1min-relay:
>         build: https://github.com/kokofixcomputers/1min-relay.git
>         command: pull kokofixcomputers/1min-relay:latest
>         environment:
>             - SUBSET_OF_ONE_MIN_PERMITTED_MODELS="mistral-nemo,gpt-4o-mini,deepseek-chat"
>             - PERMIT_MODELS_FROM_SUBSET_ONLY=True
>         ports:
>             - '5001:5001'
>         networks:
>             1min-relay-network: {}
>         container_name: 1min-relay-container
> 1min-relay-network: {}
> ```

I already have a docker compose in the repo

**Comment by JoshuaRL** [comment]
Aw man, I totally missed that. I was trying to get the docker to pull from github instead of doing a git-pull first. Here's how I got it to work, only slightly modifying your version:

```
services:
  # Memcached for storing rate-limits data.
  memcached:
    build: https://github.com/kokofixcomputers/1min-relay.git
    image: memcached:latest
    networks:
      - 1min-relay-network
    restart: unless-stopped
    # Does not require to expose port. Only used for internal communication.
  # 1min-relay
  1min-relay:
    build: https://github.com/kokofixcomputers/1min-relay.git
    image: kokofixcomputers/1min-relay:latest
    container_name: 1min-relay-container
    ports:
      - "5001:5001"
    networks:
      - 1min-relay-network
    depends_on:
      - memcached
    environment:
      # Use comma-separated string for ONE_MIN_AVAILABLE_MODELS Default: "mistral-nemo", "gpt-4o", "deepseek-chat"
      - SUBSET_OF_ONE_MIN_PERMITTED_MODELS=mistral-nemo,gpt-4o-mini,deepseek-chat
      # Set your boolean as "True" or "False" for PERMIT_MODELS_FROM_SUBSET_ONLY Default: False
      - PERMIT_MODELS_FROM_SUBSET_ONLY=False
    restart: unless-stopped

networks:
  1min-relay-network:  # Define the custom network
```
